#!/bin/bash

# 1. Load the variables from the .env file automatically if it exists
if [ -f .env ]; then
  echo "🔍 Loading environment variables from .env"
  set -a
  source .env
  set +a
else
  echo "⚠️ .env file not found. Falling back to environment variables."
fi

# Fallback to gcloud if PROJECT_ID not set in .env
if [ -z "$PROJECT_ID" ]; then
  PROJECT_ID=$(gcloud config get-value project)
fi

echo "🚀 Configuring Log Sink '${SINK_NAME}' in project: ${PROJECT_ID}..."

# 2. Create the Log Sink
gcloud logging sinks create ${SINK_NAME} \
  bigquery.googleapis.com/projects/${PROJECT_ID}/datasets/${DATASET_ID} \
  --log-filter='protoPayload.serviceName="discoveryengine.googleapis.com" AND protoPayload.methodName="google.cloud.discoveryengine.v1.EngineService.CreateEngine"' \
  --use-partitioned-tables \
  --project=${PROJECT_ID}

# 3. Grab the unique writer identity (Service Account) generated by your new sink
echo "🔍 Fetching the sink's Service Account identity..."
SINK_SA=$(gcloud logging sinks describe ${SINK_NAME} --project=${PROJECT_ID} --format='value(writerIdentity)')

echo "🔑 Granting BigQuery Data Editor access to: ${SINK_SA}..."

# 4. Grant it access to your project's BigQuery
if ! gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --member="${SINK_SA}" \
  --role="roles/bigquery.dataEditor" \
  --condition=None; then
    echo "⚠️ Failed to automatically grant IAM permission."
    echo "Please ask an IAM Admin for project '${PROJECT_ID}' to run:"
    echo "  gcloud projects add-iam-policy-binding ${PROJECT_ID} --member=\"${SINK_SA}\" --role=\"roles/bigquery.dataEditor\" --condition=None"
fi

echo "✅ Success! Future agent creation events will now stream to the '${DATASET_ID}' dataset."